on:
  push:
    branches:
    - master

name: learn-github-actions

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: ./gradlew build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_SOME_WORKFLOW_TAG }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: SSH connect with running scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER1_HOST }}
        key: ${{ secrets.SERVER1_PRIVATE_KEY }}
        username: ${{ secrets.SERVER1_SSH_USER }}
        script: |
          cd /home
          docker compose pull some-api
          docker compose up -d some-api